from typing import Any, Optional, Tuple, Union

NOTSET: int
TRACE: int
DEBUG: int
INFO: int
NOTICE: int
WARNING: int
ERROR: int
CRITICAL: int

def lookup_level(level: Union[str, int]) -> int: ...

class Logger:
    name: Optional[str]
    level: int

    def __init__(self, name: Optional[str] = None, level: int = ...) -> None: ...
    def trace(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def debug(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def info(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def warning(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def warn(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def notice(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def error(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def critical(self, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def exception(self, msg: str = ..., *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
    def log(self, level: int, msg: str, *args: object, exc_info: Optional[Any] = None, extra: Optional[Any] = None, frame_correction: int = 0) -> None: ...
