from typing import Any
from typing import Protocol
from typing import runtime_checkable


@runtime_checkable
class _LoggerProtocol(Protocol):
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> object: ...
    def info(self, msg: str, *args: Any, **kwargs: Any) -> object: ...
    def warning(self, msg: str, *args: Any, **kwargs: Any) -> object: ...
    def error(self, msg: str, *args: Any, **kwargs: Any) -> object: ...
    def exception(self, msg: str, *args: Any, **kwargs: Any) -> object: ...
    def critical(self, msg: str, *args: Any, **kwargs: Any) -> object: ...
