from typing import Protocol
from typing import runtime_checkable


@runtime_checkable
class _LoggerProtocol(Protocol):
    def debug(self, msg: str, *args: object, **kwargs: object) -> object: ...
    def info(self, msg: str, *args: object, **kwargs: object) -> object: ...
    def warning(self, msg: str, *args: object, **kwargs: object) -> object: ...
    def error(self, msg: str, *args: object, **kwargs: object) -> object: ...

    def exception(
        self, msg: str, *args: object, **kwargs: object
    ) -> object: ...

    def critical(
        self, msg: str, *args: object, **kwargs: object
    ) -> object: ...
