from collections.abc import Sequence
from types import TracebackType
from typing import Any, Union

_ExcInfo = Union[
    tuple[type[BaseException], BaseException, TracebackType | None],
    tuple[None, None, None],
    BaseException,
    bool,
    None,
]


class Logfire:
    def with_settings(self, *, custom_scope_suffix: str = ..., **kwargs: Any) -> "Logfire": ...
    def debug(self, msg: str, *, _tags: Sequence[str] | None = ..., _exc_info: _ExcInfo = ..., **attributes: Any) -> None: ...
    def info(self, msg: str, *, _tags: Sequence[str] | None = ..., _exc_info: _ExcInfo = ..., **attributes: Any) -> None: ...
    def warn(self, msg: str, *, _tags: Sequence[str] | None = ..., _exc_info: _ExcInfo = ..., **attributes: Any) -> None: ...
    def error(self, msg: str, *, _tags: Sequence[str] | None = ..., _exc_info: _ExcInfo = ..., **attributes: Any) -> None: ...
    def fatal(self, msg: str, *, _tags: Sequence[str] | None = ..., _exc_info: _ExcInfo = ..., **attributes: Any) -> None: ...
    def exception(self, msg: str, *, _tags: Sequence[str] | None = ..., _exc_info: _ExcInfo = ..., **attributes: Any) -> None: ...


def with_settings(*, custom_scope_suffix: str = ..., **kwargs: Any) -> Logfire: ...
